// =============================================================================
// EXPORT SERVICE MODULE
// Handles exporting evaluation results to JSON and Markdown
// =============================================================================

(function(window) {
  'use strict';

  /**
   * Export results as JSON file
   * @param {Object} evaluationData - Complete evaluation data with results and metadata
   * @param {string} filename - Optional filename (default: dmp-evaluation-{date}.json)
   */
  function exportAsJSON(evaluationData, filename = null) {
    const defaultFilename = `dmp-evaluation-${getDateString()}.json`;
    const finalFilename = filename || defaultFilename;

    const jsonString = JSON.stringify(evaluationData, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });

    downloadFile(blob, finalFilename);
    console.log('[Export] JSON file exported:', finalFilename);
  }

  /**
   * Export results as Markdown file
   * @param {Object} evaluationData - Complete evaluation data with results and metadata
   * @param {string} filename - Optional filename
   */
  function exportAsMarkdown(evaluationData, filename = null) {
    const defaultFilename = `dmp-evaluation-${getDateString()}.md`;
    const finalFilename = filename || defaultFilename;

    const markdown = generateMarkdown(evaluationData);
    const blob = new Blob([markdown], { type: 'text/markdown' });

    downloadFile(blob, finalFilename);
    console.log('[Export] Markdown file exported:', finalFilename);
  }

  /**
   * Generate Markdown content from evaluation data
   * @param {Object} data - Evaluation data
   * @returns {string} - Markdown content
   */
  function generateMarkdown(data) {
    const { results, metadata } = data;
    const date = new Date(metadata.evaluationDate).toLocaleDateString();
    const phase = capitalizeFirst(metadata.phase);

    let md = `# DMP Evaluation Report\n\n`;

    // Metadata section
    md += `## Evaluation Details\n\n`;
    md += `- **Date**: ${date}\n`;
    md += `- **Phase**: ${phase}\n`;
    md += `- **DMP File**: ${metadata.dmpFile}\n`;
    md += `- **Criteria File**: ${metadata.criteriaFile}\n`;
    md += `- **Model Used**: ${metadata.model || 'N/A'}\n\n`;

    // Overall Score
    md += `## Overall Compliance Score\n\n`;
    md += `**${results.overallScore}/100** `;
    md += `(${getStatusLabel(results.overallScore)})\n\n`;

    // Progress bar (visual representation)
    const barLength = 30;
    const filledLength = Math.round((results.overallScore / 100) * barLength);
    const emptyLength = barLength - filledLength;
    md += `\`[${'█'.repeat(filledLength)}${' '.repeat(emptyLength)}]\`\n\n`;

    // Summary statistics
    const summary = window.Evaluator.generateSummary(results);
    if (summary) {
      md += `### Summary Statistics\n\n`;
      md += `- Total Categories Evaluated: ${summary.totalCategories}\n`;
      md += `- Average Score: ${summary.averageScore}\n`;
      md += `- Highest Score: ${summary.maxScore}\n`;
      md += `- Lowest Score: ${summary.minScore}\n\n`;

      md += `**Performance Breakdown**:\n`;
      md += `- Excellent (90-100): ${summary.statusCounts.excellent} categories\n`;
      md += `- Good (75-89): ${summary.statusCounts.good} categories\n`;
      md += `- Pass (60-74): ${summary.statusCounts.pass} categories\n`;
      md += `- Insufficient (0-59): ${summary.statusCounts.insufficient} categories\n\n`;
    }

    // Detailed scores table
    md += `## Detailed Scores by Category\n\n`;
    md += `| ID | Category | Score | Status |\n`;
    md += `|----|----------|-------|--------|\n`;

    results.categories.forEach(cat => {
      md += `| ${cat.id} | ${cat.name} | ${cat.score}/100 | ${capitalizeFirst(cat.status)} |\n`;
    });
    md += `\n`;

    // Detailed feedback
    md += `## Detailed Feedback\n\n`;

    results.categories.forEach(cat => {
      md += `### ${cat.id}. ${cat.name}\n\n`;
      md += `**Score**: ${cat.score}/100 (${capitalizeFirst(cat.status)})\n\n`;
      md += `${cat.feedback}\n\n`;
      md += `---\n\n`;
    });

    // Strengths and weaknesses
    if (summary && (summary.strengths.length > 0 || summary.weaknesses.length > 0)) {
      md += `## Key Findings\n\n`;

      if (summary.strengths.length > 0) {
        md += `### Strengths\n\n`;
        summary.strengths.forEach(cat => {
          md += `- **${cat.name}** (${cat.score}/100): ${cat.feedback.substring(0, 150)}...\n`;
        });
        md += `\n`;
      }

      if (summary.weaknesses.length > 0) {
        md += `### Areas for Improvement\n\n`;
        summary.weaknesses.forEach(cat => {
          md += `- **${cat.name}** (${cat.score}/100): ${cat.feedback.substring(0, 150)}...\n`;
        });
        md += `\n`;
      }
    }

    // Footer
    md += `---\n\n`;
    md += `*Generated by DMP Evaluation Tool on ${new Date(metadata.evaluationDate).toLocaleString()}*\n`;

    return md;
  }

  /**
   * Download a blob as a file
   * @param {Blob} blob - Blob to download
   * @param {string} filename - Filename
   */
  function downloadFile(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  /**
   * Get date string for filename
   * @returns {string} - Date string (YYYY-MM-DD)
   */
  function getDateString() {
    const now = new Date();
    return now.toISOString().split('T')[0];
  }

  /**
   * Capitalize first letter of string
   * @param {string} str - String to capitalize
   * @returns {string} - Capitalized string
   */
  function capitalizeFirst(str) {
    if (!str) return '';
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  /**
   * Get status label from score
   * @param {number} score - Score (0-100)
   * @returns {string} - Status label
   */
  function getStatusLabel(score) {
    if (score >= 90) return 'Excellent';
    if (score >= 75) return 'Good';
    if (score >= 60) return 'Pass';
    return 'Insufficient';
  }

  // Export public API
  window.ExportService = {
    exportAsJSON,
    exportAsMarkdown
  };

})(window);
